# Site settings
title: Martin Wozniewicz
email: martin.woz@gmail.com
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://mpwoz.com" # the base hostname & protocol for your site
twitter_username: mpwoz
github_username:  mpwoz

# Build settings
markdown: kramdown
safe: true

